version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      ruby-dependencies:
          update-types:
            - "minor"
            - "patch"
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
