version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    groups:
      ruby-dependencies:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "net-pop"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
