require:
  - boxt_rubocop
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0

Rails/RakeEnvironment:
  Enabled: false

# Disabling this as, due to how we test cops (i.e. with large code snippets),
# the individual tests are always going to be a bit long.
RSpec/ExampleLength:
  Enabled: false

# Setting this to a max of 3 as 2 is too restrictive for some of our code
Style/SafeNavigationChainLength:
  Max: 3
