require:
  - rubocop-zuno

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2

Naming/FileName:
  Exclude:
    - "lib/rubocop-zuno.rb"

Rails/RakeEnvironment:
  Enabled: false

# Disabling this as, due to how we test cops (i.e. with large code snippets),
# the individual tests are always going to be a bit long.
RSpec/ExampleLength:
  Enabled: false
