AllCops:
  Exclude:
    - "**/*/schema.rb"
    - Gemfile.lock
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
  NewCops: enable

Boxt/ApiPathFormat:
  Description: "Ensure that the API path uses kebab case"
  Enabled: false

Boxt/ApiTypeParameters:
  Description: "Ensure that API parameters are typed"
  Enabled: false

Layout/ClassStructure:
  Enabled: true

Layout/LineLength:
  Exclude:
    - config/routes.rb
    - config/routes/*
  Max: 120

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*

Metrics/BlockLength:
  CountAsOne: ["array", "hash"]
  Exclude:
    - "*.gemspec"
    - Gemfile
    - config/environments/*
    - config/routes.rb
    - config/routes/*
    - db/migrate/**/*
    - lib/tasks/**/*
    - spec/**/*
    - test/**/*

Metrics/ClassLength:
  CountAsOne: ["array", "hash"]
  Exclude:
    - db/migrate/**/*
    - spec/**/*
    - test/**/*

Metrics/MethodLength:
  CountAsOne: ["array", "heredoc", "hash"]
  Exclude:
    - db/migrate/**/*
    - spec/**/*
    - test/**/*

Metrics/ModuleLength:
  CountAsOne: ["array", "hash"]

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: "always"

# Setting this to a max of 3 as 2 is too restrictive for some of our code
Style/SafeNavigationChainLength:
  Max: 3

Style/StringLiterals:
  EnforcedStyle: double_quotes
