name: CI

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.2.2"
      - run: bundle exec rubocop
      - run: bundle exec rake test
